version: '3'
services:
  app: &mainApp
    build:
      context: .
    image: keboola/wr-snowflake-workspace
    environment:
      - KBC_URL
      - KBC_TOKEN
  dev:
    <<: *mainApp
    volumes:
      - ./:/code
      - ./data:/data
